---
title: "R Notebook"
output: html_notebook
---



```{r}
library(CNORfuzzy)
data(DreamModel, package="CellNOptR")
data(CNOlistDREAM, package="CellNOptR")
```


```{r}
 # Default parameters
paramsList = defaultParametersFuzzy(CNOlistDREAM, DreamModel)
# Some Genetic Algorithm parameters
paramsList$popSize
paramsList$maxTime
paramsList$maxGens
paramsList$stallGenMax  = 50
paramsList$verbose      = FALSE
```
```{r}

# Default Fuzzy Logic Type1 parameters (Hill transfer functions)
     nrow = 7
     paramsList$type1Funs = matrix(data = NaN,nrow=nrow,ncol=3)
     paramsList$type1Funs[,1] = 1
     paramsList$type1Funs[,2] = c(3, 3, 3, 3, 3, 3, 1.01)
     paramsList$type1Funs[,3] = c(0.2, 0.3, 0.4, 0.55, 0.72,1.03, 68.5098)

```

```{r}
# Default Fuzzy Logic Type2 parameters
     nrow = 7
     paramsList$type2Funs = matrix(data = NaN,nrow=nrow,ncol=3)
     paramsList$type2Funs[,1] = seq(from=0.2, to=0.8, length=nrow)
     #paramsList$type2Funs[,1] = c(0.2,0.3,0.4,0.5,0.6,0.7,0.8)
     paramsList$type2Funs[,2] = 1
     paramsList$type2Funs[,3] = 1
```

```{r}

paramsList$redThres = c(0, 0.0001, 0.0005, 0.001,  0.003, 0.005, 0.01)
```


```{r}
paramsList$optimisation$algorithm = "NLOPT_LN_SBPLX"
     paramsList$optimisation$xtol_abs = 0.001
     paramsList$optimisation$maxeval =  10000
     paramsList$optimisation$maxtime = 60*5
```

```{r}
N = 10
allRes = list()
for (i in 1:N){
  Res = CNORwrapFuzzy(CNOlistDREAM, DreamModel, paramsList=paramsList,
    verbose=TRUE)
     allRes[[i]] = Res
 }
summary = compileMultiRes(allRes, show=TRUE)
```

```{r}

writeFuzzyNetwork(0.01, summary$allFinalMSEs, allRes, "../CNoRFuzzyData/output_dream.sif")
```

```{r}



```

```{r}
# Look into what model has best MSE to select which one we simulate with
bestmodel = allRes[[5]]

best_structure= bestmodel$processedModel
model = bestmodel$redRef[[1]]$refModel$refinedModel
simlist = bestmodel$redRef[[1]]$refModel$refinedSimList
```

```{r}
CNO_to_simulate = CNOlist(makeCNOlist(readMIDAS("input_CNO_DREAM.csv"), subfield = TRUE))

print("indeices")
indexList<-indexFinder(CNOlist=CNO_to_simulate,model=model,verbose=TRUE)
print("simulate")
simulations <- simFuzzyT1(CNO_to_simulate, model, simlist)
colnames(simulations) <- model$namesSpecies
write.table(simulations, sep = ",", file = "simulated_data_DREAM.csv")


writeSIF(model, filename = "optimised_structure_DREAM.sif")
```